[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
    "python3 -m pip install -r requirements.txt",
    "npm install --production --no-optional"
]

[start]
cmd = "python start.py"
