[phases.setup]
nixPkgs = ["python311", "nodejs_18", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python start.py"
