[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18"]

[phases.install]
cmds = [
    "pip install -r requirements.txt --break-system-packages",
    "timeout 300 npm ci --production --no-optional --no-fund --no-audit --prefer-offline || npm install --production --no-optional --no-fund --no-audit --force"
]

[start]
cmd = "python start.py"
