[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install --production --no-optional"
]

[start]
cmd = "python start.py"
