[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NODE_VERSION = "18"
